name: "CI (Integração Contínua): Primeira Action"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  exemplo: #Job: Exemplo
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Runs a list files
      run: ls -la
